package Overnet::Burner::RexBundle;

use strictures 2;

use Carp       qw(croak);
use File::Path qw(make_path);
use File::Spec;
use JSON ();

use Overnet::Burner::Util qw(clone_json json_text write_file);

our $VERSION = '0.001';

my @ROLE_FIELDS      = qw(relays publishers subscribers query_readers object_readers observers syncers sync_bridges);
my @LIFECYCLE_PHASES = qw(bootstrap deploy start warmup run chaos collect cleanup);

sub render {
  my ($class, %args) = @_;

  my $run_dir = $args{run_dir} || croak "run_dir is required\n";
  my $plan    = $args{plan}    || croak "plan is required\n";
  if (!-d $run_dir) {
    croak "run_dir does not exist: $run_dir\n";
  }

  my $mode = _mode($args{execution}, $args{inventory});
  if ($mode->{performed}) {
    $mode->{deploy_files} = _deploy_files($plan, $run_dir);
  }

  my $relative_dir = File::Spec->catdir('artifacts', 'rex');
  my $bundle_dir   = File::Spec->catdir($run_dir,    $relative_dir);
  my @actors       = _actors($plan);
  my %content      = (
    'Rexfile'                  => _rexfile($plan, $mode),
    'actor-hosts.json'         => _json(_actor_hosts(\@actors)),
    'artifact-collection.json' => _json(_artifact_collection($plan)),
    'chaos-hooks.json'         => _json({hooks => _clone($plan->{chaos_hooks} || [])}),
    'inventory/hosts.json'     => _json(_inventory(\@actors)),
    'lifecycle.json'           => _json(_lifecycle($mode)),
    'topology-provider.json'   => _json(_topology_provider($plan, $mode)),
  );

  for my $actor (@actors) {
    $content{File::Spec->catfile('actors', "$actor->{id}.json")} = _json(_actor_config($plan, $actor));
  }

  my @files = sort keys %content;
  $content{'bundle.json'} = _json(_bundle_index($plan, \@files, $mode));
  @files                  = sort keys %content;
  $content{'bundle.json'} = _json(_bundle_index($plan, \@files, $mode));

  make_path($bundle_dir, File::Spec->catdir($bundle_dir, 'actors'), File::Spec->catdir($bundle_dir, 'inventory'),);

  for my $relative_path (@files) {
    _write_file(File::Spec->catfile($bundle_dir, $relative_path), $content{$relative_path},);
  }

  return {
    relative_dir     => $relative_dir,
    files            => \@files,
    remote_execution => $mode->{remote_execution},
  };
}

# Resolve the render mode. The default is 'planned' - a rendered artifact whose
# tasks only describe what would run - so existing consumers are unaffected. A
# 'performed' render is a real, executable bundle; its reported
# remote_execution follows the target transport (ssh => remote, local => the
# controller host).
sub _mode {
  my ($execution, $inventory) = @_;

  $execution = defined $execution ? $execution : 'planned';
  if ($execution eq 'planned') {
    return {performed => 0, remote_execution => 'not_performed', inventory => {}};
  }
  if ($execution ne 'performed') {
    croak "execution must be 'planned' or 'performed'\n";
  }

  if (ref $inventory ne 'HASH') {
    croak "performed render requires an inventory hash reference\n";
  }
  my $transport = $inventory->{transport} || 'local';
  if ($transport ne 'ssh' && $transport ne 'local') {
    croak "inventory transport must be 'ssh' or 'local'\n";
  }
  if ($transport eq 'ssh' && !(defined $inventory->{host} && length $inventory->{host})) {
    croak "performed ssh render requires an inventory host\n";
  }

  return {
    performed        => 1,
    remote_execution => ($transport eq 'ssh' ? 'remote' : 'local'),
    inventory        => {%{$inventory}, transport => $transport},
  };
}

sub _actors {
  my ($plan) = @_;
  my @actors;

  for my $field (@ROLE_FIELDS) {
    push @actors, @{$plan->{$field} || []};
  }

  return @actors;
}

sub _rexfile {
  my ($plan, $mode) = @_;

  if ($mode->{performed}) {
    return _performed_rexfile($mode);
  }

  my @groups = ('all', @ROLE_FIELDS);
  my $text   = <<'REX';
# Generated by overnet-burner Rex bundle renderer.
# Rendering this bundle does not perform remote execution.

use strictures 2;

use Rex -feature => ['1.4'];

REX

  for my $group (@groups) {
    $text .= "group '$group' => 'localhost';\n";
  }

  $text .= "\n";
  for my $phase (@LIFECYCLE_PHASES) {
    $text .= <<"REX";
task '$phase', sub {
    print "planned overnet-burner phase: $phase\\n";
};

REX
  }

  return $text;
}

# A real, executable Rexfile. The 'provider_command' task runs the command it is
# handed through OVERNET_BURNER_REX_COMMAND; the optional 'deploy' task places
# the descriptor's files on the host with Rex's own file primitive. Both run
# either on the controller (local transport) or over SSH with key authentication
# (ssh transport).
sub _performed_rexfile {
  my ($mode) = @_;

  my $inventory    = $mode->{inventory}      || {};
  my $deploy_files = $mode->{deploy_files}   || [];
  my $transport    = $inventory->{transport} || 'local';
  my $text         = <<'REX';
# Generated by overnet-burner Rex bundle renderer.
# This bundle performs remote execution.

use strictures 2;

use Rex -feature => ['1.4'];

REX

  my $group_clause = q{};
  if ($transport eq 'ssh') {
    if (defined $inventory->{user} && length $inventory->{user}) {
      $text .= "user '" . _quote($inventory->{user}) . "';\n";
    }
    if (defined $inventory->{key} && length $inventory->{key}) {
      $text .= "private_key '" . _quote($inventory->{key}) . "';\n";
      $text .= "public_key '" . _quote("$inventory->{key}.pub") . "';\n";
    }
    $text .= "key_auth;\n\n";

    my $host = $inventory->{host};
    if (defined $inventory->{port} && $inventory->{port} =~ /\A[1-9][0-9]*\z/mxs && $inventory->{port} != 22) {
      $host = "$host:$inventory->{port}";
    }
    $text .= "group 'relays' => '" . _quote($host) . "';\n\n";
    $group_clause = " group => 'relays',";
  }

  if (@{$deploy_files}) {
    $text .= "task 'deploy',$group_clause sub {\n";
    for my $file (@{$deploy_files}) {
      $text .= "    file '" . _quote($file->{dest}) . "',\n";
      $text .= "      source => '" . _quote($file->{source}) . "';\n";
    }
    $text .= "};\n\n";
  }

  $text .= <<"REX";
task 'provider_command',$group_clause sub {
    my \$output = run \$ENV{OVERNET_BURNER_REX_COMMAND};
    if (defined \$output && length \$output) {
        print "\$output\\n";
    }
    if (\$? != 0) {
        die "provider command exited with status \$?\\n";
    }
};
REX

  return $text;
}

# Collect the deploy files declared by the plan's relay descriptors, resolving
# each controller-side source to an absolute path (relative sources resolve
# against the run directory, since Rex runs from the bundle directory).
sub _deploy_files {
  my ($plan, $run_dir) = @_;

  my $absolute_run_dir = File::Spec->rel2abs($run_dir);
  my @files;
  for my $relay (@{$plan->{relays} || []}) {
    my $deploy = $relay->{topology_provider_descriptor}{deploy};
    if (ref $deploy ne 'HASH') {
      next;
    }
    for my $file (@{$deploy->{files} || []}) {
      my $source =
        File::Spec->file_name_is_absolute($file->{source})
        ? $file->{source}
        : File::Spec->rel2abs($file->{source}, $absolute_run_dir);
      push @files, {dest => $file->{dest}, source => $source};
    }
  }

  return \@files;
}

sub _quote {
  my ($value) = @_;

  $value =~ s/\\/\\\\/gmxs;
  $value =~ s/'/\\'/gmxs;
  return $value;
}

sub _inventory {
  my ($actors) = @_;
  my %groups = map { $_ => [] } ('all', @ROLE_FIELDS);

  if (@{$actors}) {
    push @{$groups{all}}, 'host-001';
  }
  for my $field (@ROLE_FIELDS) {
    my $role = _field_role($field);
    if (_has_actor_role($actors, $role)) {
      push @{$groups{$field}}, 'host-001';
    }
  }

  return {
    groups => \%groups,
    hosts  => [
      {
        id       => 'host-001',
        hostname => 'localhost',
      },
    ],
  };
}

sub _actor_hosts {
  my ($actors) = @_;

  return {assignments => [map { {actor_id => $_->{id}, host_id => 'host-001', role => $_->{role},} } @{$actors}],};
}

sub _actor_config {
  my ($plan, $actor) = @_;

  return {
    actor   => _clone($actor),
    env     => _actor_env($plan, $actor),
    host_id => 'host-001',
    exists $actor->{metric_stream} ? (metric_stream => $actor->{metric_stream}) : (),
  };
}

sub _actor_env {
  my ($plan, $actor) = @_;

  return {
    OVERNET_BURNER_ACTOR_ID          => $actor->{id},
    OVERNET_BURNER_ROLE              => $actor->{role},
    OVERNET_BURNER_RUN_NAME          => $plan->{run}{name},
    OVERNET_BURNER_SEED              => "$actor->{seed}",
    OVERNET_BURNER_TOPOLOGY_PROVIDER => $plan->{topology_provider}{name},
  };
}

sub _lifecycle {
  my ($mode) = @_;
  my $execution = $mode->{performed} ? 'performed' : 'planned';

  my @commands;
  my $ordinal = 0;

  for my $phase (@LIFECYCLE_PHASES) {
    $ordinal++;
    push @commands,
      {
      id        => sprintf('lifecycle-%03d', $ordinal),
      execution => $execution,
      phase     => $phase,
      rex_task  => $phase,
      };
  }

  return {commands => \@commands};
}

sub _topology_provider {
  my ($plan, $mode) = @_;

  return {
    topology_provider => _clone($plan->{topology_provider} || {}),
    relays            => [map { _topology_provider_relay($_, $mode) } @{$plan->{relays} || []},],
  };
}

sub _topology_provider_relay {
  my ($relay, $mode) = @_;
  my $execution = $mode->{performed} ? 'performed' : 'planned';

  my $relay_record = {actor_id => $relay->{id},};
  my $descriptor   = $relay->{topology_provider_descriptor} || {};
  my $command      = $descriptor->{command};
  if ($command) {
    $relay_record->{lifecycle} = {
      health => {
        command   => $command->{health},
        execution => $execution,
      },
      start => {
        command   => $command->{start},
        execution => $execution,
      },
      stop => {
        command   => $command->{stop},
        execution => $execution,
      },
    };
  }

  my $deploy = $descriptor->{deploy};
  if (ref $deploy eq 'HASH') {
    $relay_record->{deploy} = {
      files     => _clone($deploy->{files} || []),
      execution => $execution,
    };
  }

  return $relay_record;
}

sub _has_actor_role {
  my ($actors, $role) = @_;

  for my $actor (@{$actors}) {
    if ($actor->{role} eq $role) {
      return 1;
    }
  }

  return 0;
}

sub _artifact_collection {
  my ($plan) = @_;

  return {
    files => [
      {
        id     => 'runner-log',
        source => 'logs/runner.jsonl',
      },
      {
        id     => 'metrics',
        source => 'metrics.jsonl',
      },
    ],
    metric_streams => _clone($plan->{metric_streams} || []),
  };
}

sub _bundle_index {
  my ($plan, $files, $mode) = @_;

  return {
    bundle => {
      name    => 'overnet-burner-rex',
      version => 1,
    },
    execution => {
      remote_execution => $mode->{remote_execution},
    },
    files       => $files,
    source_plan => {
      path         => 'plan.json',
      plan_version => $plan->{plan_version},
      scenario     => $plan->{scenario}{name},
    },
  };
}

sub _field_role {
  my ($field) = @_;

  my %role = (
    relays         => 'relay',
    publishers     => 'publisher',
    subscribers    => 'subscriber',
    query_readers  => 'query_reader',
    object_readers => 'object_reader',
    observers      => 'observer',
    syncers        => 'syncer',
    sync_bridges   => 'sync_bridge',
  );

  return $role{$field};
}

sub _json {
  my ($value) = @_;

  return json_text($value);
}

sub _clone {
  my ($value) = @_;

  return clone_json($value);
}

sub _write_file {
  my ($path, $content) = @_;

  write_file($path, $content);
  return;
}

1;

=head1 NAME

Overnet::Burner::RexBundle - Rex execution bundle renderer

=head1 DESCRIPTION

Renders deterministic Rex bundle artifacts for an overnet-burner execution plan.

=head1 VERSION

Version 0.001.

=head1 SYNOPSIS

  my $bundle = Overnet::Burner::RexBundle->render(%args);

=head1 SUBROUTINES/METHODS

=head2 render

=head1 DIAGNOSTICS

Missing run directories or invalid arguments are reported through exceptions.

=head1 CONFIGURATION AND ENVIRONMENT

No environment configuration is required for rendering.

=head1 DEPENDENCIES

See the distribution metadata for runtime dependencies.

=head1 INCOMPATIBILITIES

No known incompatibilities are documented.

=head1 BUGS AND LIMITATIONS

No known bugs are documented.

=head1 AUTHOR

Overnet Project.

=head1 LICENSE AND COPYRIGHT

See the project license.

=cut
